export const PRODUCT_CATEGORIES = [
  // Electronics & Technology
  "Smartphones & Tablets",
  "Laptops & Computers",
  "Computer Accessories",
  "Cameras & Photography",
  "Audio & Headphones",
  "Smart Home Devices",
  "Wearable Technology",
  "Gaming Consoles",
  "Gaming Accessories",
  "Drones & Accessories",
  "Virtual Reality",
  "3D Printers",
  "Electronic Components",
  "Cables & Adapters",
  "Power Banks & Chargers",
  "Smart Watches",
  "TV & Home Theater",
  "Projectors & Screens",
  "Security Cameras",
  "Networking Equipment",
  
  // Fashion & Apparel
  "Men's Clothing",
  "Women's Clothing",
  "Kids' Clothing",
  "Baby Clothing",
  "Shoes & Footwear",
  "Bags & Luggage",
  "Watches & Jewelry",
  "Sunglasses & Eyewear",
  "Hats & Caps",
  "Belts & Accessories",
  "Swimwear",
  "Activewear & Sportswear",
  "Traditional Clothing",
  "Wedding Attire",
  "Maternity Clothing",
  "Plus Size Fashion",
  "Formal Wear",
  "Casual Wear",
  "Uniforms",
  "Costumes & Fancy Dress",
  
  // Home & Living
  "Furniture",
  "Home Decor",
  "Bedding & Linens",
  "Kitchen & Dining",
  "Cookware & Bakeware",
  "Small Kitchen Appliances",
  "Storage & Organization",
  "Lighting & Lamps",
  "Curtains & Blinds",
  "Rugs & Carpets",
  "Wall Art & Mirrors",
  "Home Improvement",
  "Tools & Hardware",
  "Bathroom Accessories",
  "Garden & Outdoor",
  "Plants & Seeds",
  "Garden Tools",
  "Outdoor Furniture",
  "BBQ & Grills",
  "Pool & Hot Tub",
  
  // Health & Beauty
  "Skincare Products",
  "Makeup & Cosmetics",
  "Hair Care",
  "Fragrances & Perfumes",
  "Personal Care",
  "Health Supplements",
  "Vitamins & Minerals",
  "Fitness Equipment",
  "Yoga & Pilates",
  "Medical Supplies",
  "First Aid",
  "Massage & Relaxation",
  "Weight Management",
  "Oral Care",
  "Men's Grooming",
  "Nail Care",
  "Beauty Tools",
  "Natural & Organic Beauty",
  
  // Sports & Outdoors
  "Exercise & Fitness",
  "Cycling & Bikes",
  "Camping & Hiking",
  "Fishing Equipment",
  "Team Sports",
  "Water Sports",
  "Winter Sports",
  "Martial Arts",
  "Boxing & MMA",
  "Tennis & Racquet Sports",
  "Golf Equipment",
  "Running & Jogging",
  "Skateboarding",
  "Scooters",
  "Sports Nutrition",
  "Sports Apparel",
  "Outdoor Recreation",
  "Hunting & Shooting",
  
  // Automotive
  "Car Accessories",
  "Car Electronics",
  "Car Care & Cleaning",
  "Motorcycle Parts",
  "Tires & Wheels",
  "Car Audio & Video",
  "GPS & Navigation",
  "Auto Body Parts",
  "Engine Components",
  "Tools & Equipment",
  "Interior Accessories",
  "Exterior Accessories",
  "Performance Parts",
  "Lighting & Lamps",
  "Safety & Security",
  
  // Baby & Kids
  "Baby Food & Formula",
  "Diapers & Wipes",
  "Baby Care",
  "Nursing & Feeding",
  "Baby Toys",
  "Strollers & Car Seats",
  "Baby Furniture",
  "Baby Monitors",
  "Kids Toys & Games",
  "Educational Toys",
  "Outdoor Play Equipment",
  "Arts & Crafts",
  "Building Blocks",
  "Dolls & Stuffed Animals",
  "Action Figures",
  "Board Games",
  "Puzzles",
  
  // Books & Media
  "Fiction Books",
  "Non-Fiction Books",
  "Educational Books",
  "Children's Books",
  "Comics & Graphic Novels",
  "Magazines",
  "E-Books",
  "Audiobooks",
  "Movies & DVDs",
  "Music CDs & Vinyl",
  "Musical Instruments",
  "Sheet Music",
  
  // Food & Beverages
  "Fresh Produce",
  "Meat & Seafood",
  "Dairy Products",
  "Bakery Items",
  "Snacks & Sweets",
  "Beverages",
  "Coffee & Tea",
  "Canned & Packaged Foods",
  "Organic Foods",
  "International Cuisine",
  "Spices & Seasonings",
  "Cooking Oils",
  "Baby Food",
  "Pet Food",
  
  // Office & Stationery
  "Office Supplies",
  "Stationery & Paper",
  "Writing Instruments",
  "Office Furniture",
  "Office Electronics",
  "Printers & Scanners",
  "Filing & Organization",
  "Presentation Supplies",
  "School Supplies",
  "Art Supplies",
  "Craft Materials",
  "Sewing & Fabric",
  
  // Pets & Animals
  "Dog Food & Treats",
  "Cat Food & Treats",
  "Pet Toys",
  "Pet Grooming",
  "Pet Carriers & Travel",
  "Pet Beds & Furniture",
  "Aquarium & Fish Supplies",
  "Bird Supplies",
  "Small Animal Supplies",
  "Pet Health & Wellness",
  "Pet Training & Behavior",
  
  // Jewelry & Accessories
  "Necklaces",
  "Rings",
  "Bracelets",
  "Earrings",
  "Brooches & Pins",
  "Fine Jewelry",
  "Fashion Jewelry",
  "Precious Stones",
  "Custom Jewelry",
  "Jewelry Storage",
  
  // Industrial & Scientific
  "Industrial Tools",
  "Lab Equipment",
  "Testing Instruments",
  "Safety Equipment",
  "Industrial Supplies",
  "Packaging Materials",
  "Commercial Kitchen Equipment",
  "Medical Equipment",
  "Construction Materials",
  "Agricultural Equipment",
  
  // Other
  "Handmade & Crafts",
  "Collectibles & Antiques",
  "Art & Paintings",
  "Religious Items",
  "Party Supplies",
  "Gift Items",
  "Services",
  "Digital Products",
  "Software & Apps",
  "Gift Cards & Vouchers",
].sort();
